import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const save = vi.fn();
const regenerate = vi.fn();
vi.mock("@/hooks/use-article-metadata", () => ({
  useArticleMetadata: () => ({
    save,
    saving: false,
    regenerate,
    regenerating: false,
  }),
}));

import { ArticleHeaderEditor } from "./article-header-editor";
import type { ArticleDetail } from "@/types/articles";

const article = {
  id: "a1",
  title: "Original title",
  subtitle: "Original subtitle",
  status: "draft",
  seo: {
    title: "Original SEO title",
    description: "Original SEO description",
    keywords: ["one", "two"],
  },
} as unknown as ArticleDetail;

beforeEach(() => {
  vi.clearAllMocks();
  save.mockResolvedValue({
    id: "a1",
    title: "Changed",
    subtitle: "Original subtitle",
    seo: { title: "Original SEO title", description: "Original SEO description", keywords: ["one", "two"] },
    warnings: [{ field: "seo_title", message: "seo_title is 18 chars; 50-60 recommended" }],
  });
  regenerate.mockResolvedValue({
    field: "seo_title",
    value: "A proposed SEO title regenerated by the model here",
    warnings: [],
  });
});

describe("ArticleHeaderEditor", () => {
  it("renders title and subtitle in view mode", () => {
    render(<ArticleHeaderEditor article={article} />);
    expect(screen.getByText("Original title")).toBeInTheDocument();
    expect(screen.getByText("Original subtitle")).toBeInTheDocument();
    expect(screen.queryByLabelText("SEO title")).not.toBeInTheDocument();
  });

  it("prefills inputs when entering edit mode", () => {
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    expect(screen.getByLabelText("Title")).toHaveValue("Original title");
    expect(screen.getByLabelText("SEO title")).toHaveValue("Original SEO title");
    expect(screen.getByLabelText("Keywords")).toHaveValue("one, two");
  });

  it("shows an out-of-range counter for a short SEO title", () => {
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    const counter = screen.getByTestId("seo-title-counter");
    expect(counter.textContent).toContain("18/50–60");
    expect(counter.className).toContain("text-warning");
  });

  it("saves only changed fields and renders returned warnings", async () => {
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    fireEvent.change(screen.getByLabelText("Title"), {
      target: { value: "Changed" },
    });
    fireEvent.click(screen.getByRole("button", { name: /^save$/i }));
    await waitFor(() => expect(save).toHaveBeenCalledWith({ title: "Changed" }));
    expect(
      await screen.findByText(/seo_title is 18 chars; 50-60 recommended/),
    ).toBeInTheDocument();
  });

  it("disables save when nothing changed", () => {
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    expect(screen.getByRole("button", { name: /^save$/i })).toBeDisabled();
  });

  it("shows an error line when the save fails", async () => {
    save.mockRejectedValue(new Error("boom"));
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    fireEvent.change(screen.getByLabelText("Title"), {
      target: { value: "Changed" },
    });
    fireEvent.click(screen.getByRole("button", { name: /^save$/i }));
    expect(await screen.findByRole("alert")).toHaveTextContent(/save failed/i);
    // still in edit mode so the user can fix and retry
    expect(screen.getByLabelText("Title")).toBeInTheDocument();
  });

  it("shows the current status badge and the next-step transition", async () => {
    render(<ArticleHeaderEditor article={article} />);
    expect(screen.getByText("Draft")).toBeInTheDocument();
    fireEvent.click(
      screen.getByRole("button", { name: /move to in review/i }),
    );
    await waitFor(() =>
      expect(save).toHaveBeenCalledWith({ status: "in_review" }),
    );
  });

  it("published articles show no next-step button", () => {
    render(
      <ArticleHeaderEditor
        article={{ ...article, status: "published" } as unknown as ArticleDetail}
      />,
    );
    expect(screen.getByText("Published")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /move to/i })).toBeNull();
  });

  it("fills the SEO title input from a regenerate", async () => {
    render(<ArticleHeaderEditor article={article} />);
    fireEvent.click(screen.getByRole("button", { name: /edit metadata/i }));
    fireEvent.click(screen.getByRole("button", { name: /regenerate seo title/i }));
    await waitFor(() =>
      expect(screen.getByLabelText("SEO title")).toHaveValue(
        "A proposed SEO title regenerated by the model here",
      ),
    );
    expect(regenerate).toHaveBeenCalledWith("seo_title");
    expect(save).not.toHaveBeenCalled();
  });
});
