"""Unit tests for _apply_voice / persist_pipeline_result voice mapping (AUTHOR-011)."""

from datetime import UTC, datetime
from uuid import UUID, uuid4

import pytest

from src.models.content import ContentType, Provenance, SEOMetadata
from src.models.content_pipeline import (
    ArticleOutline,
    OutlineSection,
    SectionDraft,
    SEOResult,
)
from src.models.research_db import ResearchSession
from src.services.content.persist import PersistContext, persist_pipeline_result
from src.services.content_repositories import (
    ContentRepositories,
    InMemoryArticleDraftRepository,
    InMemoryArticleRepository,
)
from src.services.research import InMemoryResearchSessionRepository


def _outline() -> ArticleOutline:
    return ArticleOutline(
        title="Test Article",
        subtitle="A subtitle",
        content_type=ContentType.ARTICLE,
        sections=[
            OutlineSection(
                index=0,
                title="Intro",
                description="d",
                key_points=["a"],
                target_word_count=200,
                relevant_facets=[0],
            ),
        ],
        total_target_words=200,
        reasoning="because",
    )


def _section_drafts() -> list[SectionDraft]:
    return [
        SectionDraft(
            section_index=0,
            title="Intro",
            body_markdown="## Intro\n\nSome body text.\n",
            word_count=4,
            citations_used=[],
        ),
    ]


def _seo_result(session_id: UUID) -> SEOResult:
    return SEOResult(
        seo=SEOMetadata(title="T", description="D"),
        summary="Summary.",
        key_claims=[],
        ai_disclosure="This article was generated by AI.",
        provenance=Provenance(
            research_session_id=session_id,
            primary_model="claude-opus-4-5",
            drafting_model="claude-sonnet-4-5",
            embedding_model="all-MiniLM-L6-v2",
            embedding_version="1.0.0",
        ),
    )


def _session() -> ResearchSession:
    return ResearchSession(
        id=uuid4(),
        topic_id=uuid4(),
        status="generating_article",
        topic_title="Test Topic",
        topic_domain="cybersecurity",
        started_at=datetime.now(UTC),
    )


def _ctx() -> PersistContext:
    repos = ContentRepositories(
        drafts=InMemoryArticleDraftRepository(),
        research=InMemoryResearchSessionRepository(),
        articles=InMemoryArticleRepository(),
    )
    return PersistContext(repos=repos, settings=None)


@pytest.mark.asyncio
async def test_persist_pipeline_result_carries_voice_fields_when_present() -> None:
    session = _session()
    voice_persona_id = uuid4()
    sample_id = uuid4()
    result: dict[str, object] = {
        "outline": _outline(),
        "section_drafts": _section_drafts(),
        "total_word_count": 4,
        "seo_result": _seo_result(session.id),
        "voice_persona_id": voice_persona_id,
        "voice_match_score": 88,
        "voice_scores_by_section": {"0": 88},
        "few_shot_sample_ids": [sample_id],
    }

    article = await persist_pipeline_result(_ctx(), session, result)

    assert article.voice_persona_id == voice_persona_id
    assert article.voice_match_score == 88
    assert article.voice_scores_by_section == {"0": 88}
    assert article.few_shot_sample_ids == [sample_id]


@pytest.mark.asyncio
async def test_persist_pipeline_result_defaults_voice_fields_when_absent() -> None:
    session = _session()
    result: dict[str, object] = {
        "outline": _outline(),
        "section_drafts": _section_drafts(),
        "total_word_count": 4,
        "seo_result": _seo_result(session.id),
    }

    article = await persist_pipeline_result(_ctx(), session, result)

    assert article.voice_persona_id is None
    assert article.voice_match_score is None
    assert article.voice_scores_by_section is None
    assert article.few_shot_sample_ids == []
