"""Slop phrase database — 200+ AI writing signals.

Categorized phrases ported from slop-radar (MIT license).
Used by the slop scorer to detect AI-generated text patterns.
"""

SLOP_PHRASES: dict[str, list[str]] = {
    "buzzwords": [
        "dive into", "dive deep", "deep dive", "delve", "delve into",
        "crucial", "landscape", "robust", "leverage",
        "game-changer", "game-changing", "cutting-edge", "state-of-the-art",
        "revolutionize", "revolutionary", "transformative",
        "seamless", "seamlessly", "comprehensive", "holistic", "noteworthy",
        "innovative", "versatile", "foster", "streamline",
        "optimize", "enhance", "harness", "unlock",
        "curate", "curated", "tailored", "bespoke",
        "empower", "empowering", "synergy", "paradigm shift", "paradigm",
        "ecosystem", "unpack", "utilize", "catalyze",
        "orchestrate", "reimagine", "democratize",
        "operationalize", "incentivize", "contextualize", "strategize",
        "elevate", "amplify", "resonate", "ideate",
        "disrupt", "disruption", "disruptive", "spearhead", "bolster",
    ],
    "transitions": [
        "moreover", "furthermore", "in addition", "additionally",
        "in conclusion", "to summarize", "ultimately",
        "last but not least", "firstly", "secondly", "thirdly",
        "in this regard", "to that end", "with that being said",
        "that being said", "having said that", "with that in mind",
        "by the same token", "on the flip side",
    ],
    "hedges": [
        "essentially", "fundamentally",
        "it is worth noting", "it's worth noting",
        "interestingly", "indeed", "in other words", "that said",
        "it is important to note", "it's important to note",
        "needless to say", "arguably", "it could be argued",
        "one might say", "it bears mentioning", "it should be noted",
        "it goes without saying", "all things considered",
        "it's no secret that", "while it's true that",
        "by and large", "for all intents and purposes",
    ],
    "ai_openers": [
        "let me break this down", "let me explain",
        "let me walk you through", "here's the thing",
        "here's what you need to know", "here's the deal",
        "let's unpack",
    ],
    "overblown": [
        "unprecedented", "unparalleled", "remarkable", "exceptional",
        "world-class", "best-in-class", "future-proof",
        "bleeding edge", "next-level", "groundbreaking",
        "trailblazing", "pioneering", "thought-provoking",
        "insightful", "profound", "meticulous", "meticulously",
        "intricate", "intricacies", "pivotal", "paramount",
        "indispensable", "imperative", "scalable", "actionable",
        "impactful", "thought leadership", "mission-critical", "deep-seated",
    ],
    "corporate": [
        "stakeholder", "bandwidth", "low-hanging fruit",
        "move the needle", "north star", "value-add",
        "drill down", "level up", "take it to the next level",
        "on the same page", "reach out", "touch base",
        "loop in", "take offline", "circle back", "double down", "pivot",
        "pain point", "pain points", "value proposition",
        "end-to-end", "turnkey", "plug and play", "one-stop shop",
        "win-win", "synergize", "iterate", "iterate on",
        "hands-on", "real-world", "soup to nuts",
        "from the ground up", "out of the box",
        "above and beyond", "best practices",
    ],
    "fluff": [
        "in today's world", "in today's fast-paced",
        "as we navigate", "navigate the complexities",
        "navigate the landscape", "ever-evolving", "ever-changing",
        "fast-paced", "rapidly evolving",
        "dynamic landscape", "shifting landscape",
        "in the realm of", "at the forefront",
        "pave the way", "shed light on", "stand out from the crowd",
        "rest assured", "without further ado", "when it comes to",
        "in light of", "the bottom line", "at its core",
        "at the heart of", "on a broader scale", "in the grand scheme",
        "the crux of the matter", "in a nutshell", "to put it simply",
        "in essence", "nuanced", "nuanced approach",
        "myriad", "myriad of", "plethora",
        "a plethora of", "a myriad of",
        "overarching", "underscore", "underscores", "multifaceted",
        "akin to", "serves as a testament", "stands as a testament",
        "a testament to", "not only...but also",
        "the elephant in the room", "moving forward",
    ],
    "meta": [
        "in this article", "in this post", "in this guide",
        "in this blog", "in this piece", "in this section",
        "in this tutorial", "in this overview", "in this essay",
        "comprehensive guide", "definitive guide",
        "ultimate guide", "step-by-step guide",
        "key takeaway", "key takeaways", "the takeaway",
        "wrapping up", "to wrap up", "in summary", "to sum up",
        "all in all", "food for thought", "at the end of the day",
        "robust framework", "robust solution", "holistic approach",
    ],
}
