"""Persist a content-pipeline graph result into an ArticleDraft +
CanonicalArticle.

Extracted from `ContentService.generate_full_article` so the outline
gate's `generate_from_outline` can share exactly the same persistence
logic (L-001: `model_dump(mode="json")` for JSONB storage).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

import structlog

from src.config.settings import Settings
from src.models.content import CanonicalArticle, Provenance, SEOMetadata
from src.models.content_pipeline import (
    ArticleDraft,
    ArticleOutline,
    DraftStatus,
    SEOResult,
)
from src.models.research_db import ResearchSession
from src.services.content.graph_state import build_topic_input
from src.services.content_finalize import build_article, store_article
from src.services.content_repositories import ContentRepositories, aggregate_citations

logger = structlog.get_logger()


@dataclass(frozen=True)
class PersistContext:
    """Bundled dependencies for persisting a pipeline result."""

    repos: ContentRepositories
    settings: Settings | None = None


async def persist_pipeline_result(
    ctx: PersistContext,
    session: ResearchSession,
    result: dict[str, object],
) -> CanonicalArticle:
    """Persist a completed content-pipeline result and finalize the article."""
    outline = _extract_outline(result)
    _warn_if_partial_failure(result)
    draft = await _build_draft(ctx.repos, session, outline)
    draft = await _apply_pipeline_outputs(ctx, draft, outline, result)
    topic = build_topic_input(session)
    article = build_article(draft, topic)
    article = await store_article(ctx.repos, draft, article)
    logger.info("article_finalized", article_id=str(article.id), title=article.title)
    return article


def _extract_outline(result: dict[str, object]) -> ArticleOutline:
    if result.get("outline") is None:
        raise ValueError(result.get("error", "Content pipeline failed"))
    outline = result["outline"]
    if not isinstance(outline, ArticleOutline):
        outline = ArticleOutline.model_validate(outline)
    logger.info("outline_generated", section_count=len(outline.sections))
    return outline


def _warn_if_partial_failure(result: dict[str, object]) -> None:
    if result.get("status") == "failed":
        logger.warning(
            "content_pipeline_partial_failure",
            error=str(result.get("error", "")),
            hint="Continuing with available outputs.",
        )


async def _build_draft(
    repos: ContentRepositories,
    session: ResearchSession,
    outline: ArticleOutline,
) -> ArticleDraft:
    draft = ArticleDraft(
        session_id=session.id,
        topic_id=session.topic_id,
        outline=outline,
        status=DraftStatus.DRAFT_COMPLETE,
        created_at=datetime.now(UTC),
        completed_at=datetime.now(UTC),
    )
    return await repos.drafts.create(draft)


def _jsonable(items: list[object]) -> list[object]:
    """Serialize Pydantic objects for JSONB storage (L-001)."""
    return [i.model_dump(mode="json") if hasattr(i, "model_dump") else i for i in items]


def _ensure_seo_result(
    settings: Settings | None,
    outline: ArticleOutline,
    result: dict[str, object],
) -> SEOResult:
    seo_result = result.get("seo_result")
    if seo_result is not None and not isinstance(seo_result, SEOResult):
        seo_result = SEOResult.model_validate(seo_result)
    if seo_result is not None:
        return seo_result
    logger.warning("seo_fallback_used", title=outline.title)
    return _build_seo_fallback(settings, outline)


def _build_seo_fallback(
    settings: Settings | None, outline: ArticleOutline
) -> SEOResult:
    return SEOResult(
        seo=SEOMetadata(
            title=outline.title[:70],
            description=(
                outline.subtitle[:170] if outline.subtitle else outline.title[:170]
            ),
            keywords=[],
        ),
        summary=outline.subtitle or outline.title,
        key_claims=[],
        ai_disclosure="This article was generated by AI.",
        provenance=_build_provenance(settings),
    )


def _build_provenance(settings: Settings | None) -> Provenance:
    return Provenance(
        primary_model=settings.primary_model_name if settings else "unknown",
        drafting_model=settings.drafting_model_name if settings else "unknown",
        embedding_model=settings.embedding_model if settings else "unknown",
        embedding_version=settings.embedding_version if settings else "v1",
    )


async def _apply_pipeline_outputs(
    ctx: PersistContext,
    draft: ArticleDraft,
    outline: ArticleOutline,
    result: dict[str, object],
) -> ArticleDraft:
    seo_result = _ensure_seo_result(ctx.settings, outline, result)
    raw_drafts = result.get("section_drafts", [])
    drafts_list = list(raw_drafts) if isinstance(raw_drafts, list) else []
    citations = aggregate_citations(drafts_list)
    updated = draft.model_copy(
        update={
            "section_drafts": _jsonable(drafts_list),
            "citations": _jsonable(citations),
            "total_word_count": result.get("total_word_count", 0),
            "seo_result": seo_result,
            "global_citations": _jsonable(list(result.get("global_citations") or [])),
            "references_markdown": str(result.get("references_markdown", "")),
            "visuals": _jsonable(list(result.get("visuals") or [])),
        }
    )
    draft = await ctx.repos.drafts.update(updated)
    logger.info(
        "draft_stored",
        draft_id=str(draft.id),
        word_count=draft.total_word_count,
        sections=len(drafts_list),
    )
    return draft
