"""add settings tables

Revision ID: 5cc5207085ff
Revises: 87b0f2f69269
Create Date: 2026-03-24 13:25:44.900627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc5207085ff'
down_revision: Union[str, Sequence[str], None] = '87b0f2f69269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.String(length=500), nullable=False),
    sa.Column('masked_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_service'), 'api_keys', ['service'], unique=False)
    op.create_table('domain_configs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trend_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('general_configs',
    sa.Column('article_length_target', sa.String(length=50), nullable=False),
    sa.Column('content_tone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_configs',
    sa.Column('primary_model', sa.String(length=100), nullable=False),
    sa.Column('drafting_model', sa.String(length=100), nullable=False),
    sa.Column('image_generation', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_defaults',
    sa.Column('auto_meta_tags', sa.Boolean(), nullable=False),
    sa.Column('keyword_optimization', sa.Boolean(), nullable=False),
    sa.Column('auto_cover_images', sa.Boolean(), nullable=False),
    sa.Column('include_citations', sa.Boolean(), nullable=False),
    sa.Column('human_review_before_publish', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_defaults')
    op.drop_table('llm_configs')
    op.drop_table('general_configs')
    op.drop_table('domain_configs')
    op.drop_index(op.f('ix_api_keys_service'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
