"""Tests for article assembler — CanonicalArticle from pipeline outputs."""

from datetime import UTC, datetime
from uuid import uuid4

from src.agents.content.article_assembler import assemble_canonical_article
from src.models.content import (
    CanonicalArticle,
    ContentType,
    ImageAsset,
    Provenance,
    SEOMetadata,
)
from src.models.content_pipeline import (
    ArticleDraft,
    ArticleOutline,
    DraftStatus,
    OutlineSection,
    SectionDraft,
    SEOResult,
)
from src.models.research import TopicInput


def _make_topic() -> TopicInput:
    return TopicInput(
        id=uuid4(),
        title="AI Security Trends",
        description="Emerging threats in AI systems",
        domain="tech",
    )


def _make_seo_result() -> SEOResult:
    return SEOResult(
        seo=SEOMetadata(
            title="AI Security Trends 2026",
            description="A comprehensive look at emerging AI security threats.",
            keywords=["ai", "security", "trends"],
        ),
        summary="AI security is evolving rapidly with new threat vectors.",
        key_claims=[
            "Prompt injection is the top threat [1]",
            "Model poisoning attacks increased 300% [2]",
        ],
        provenance=Provenance(
            research_session_id=uuid4(),
            primary_model="claude-opus-4",
            drafting_model="claude-sonnet-4",
            embedding_model="all-MiniLM-L6-v2",
            embedding_version="1.0.0",
        ),
        ai_disclosure="This article was generated by AI.",
    )


def _make_section(index: int, word_count: int = 400) -> SectionDraft:
    words = " ".join(["word"] * word_count)
    return SectionDraft(
        section_index=index,
        title=f"Section {index}",
        body_markdown=words,
        word_count=word_count,
        citations_used=[],
    )


def _make_outline() -> ArticleOutline:
    return ArticleOutline(
        title="AI Security Trends",
        subtitle="A deep dive",
        content_type=ContentType.ARTICLE,
        sections=[
            OutlineSection(
                index=i,
                title=f"Section {i}",
                description=f"Description {i}",
                key_points=["point"],
                target_word_count=400,
                relevant_facets=[0],
            )
            for i in range(4)
        ],
        total_target_words=1600,
        reasoning="Good structure",
    )


def _make_global_citations(count: int = 5) -> list[dict[str, object]]:
    return [
        {
            "index": i + 1,
            "title": f"Source {i}",
            "url": f"https://src{i}.com",
            "authors": [],
            "published_at": None,
        }
        for i in range(count)
    ]


def _make_draft() -> ArticleDraft:
    return ArticleDraft(
        session_id=uuid4(),
        topic_id=uuid4(),
        outline=_make_outline(),
        status=DraftStatus.COMPLETE,
        created_at=datetime.now(UTC),
        section_drafts=[_make_section(i, 400) for i in range(4)],
        total_word_count=1600,
        seo_result=_make_seo_result(),
        global_citations=_make_global_citations(5),
        references_markdown="## References\n\n[1] Source 0\n[2] Source 1",
    )


class TestAssembleCanonicalArticle:
    def test_happy_path(self) -> None:
        topic = _make_topic()
        draft = _make_draft()
        article = assemble_canonical_article(draft, topic)

        assert isinstance(article, CanonicalArticle)
        assert article.title == draft.outline.title  # type: ignore[union-attr]
        assert article.domain == "tech"
        assert article.ai_generated is True

    def test_body_has_h2_headings(self) -> None:
        article = assemble_canonical_article(_make_draft(), _make_topic())

        for i in range(4):
            assert f"## Section {i}" in article.body_markdown

    def test_body_has_references_section(self) -> None:
        article = assemble_canonical_article(_make_draft(), _make_topic())

        assert "## References" in article.body_markdown
        assert (
            article.body_markdown.rstrip().endswith(
                _make_draft().references_markdown.rstrip()
            )
            or "## References" in article.body_markdown
        )

    def test_citations_from_global_citations(self) -> None:
        draft = _make_draft()
        article = assemble_canonical_article(draft, _make_topic())

        assert len(article.citations) == 5
        assert article.citations[0].title == "Source 0"
        assert article.citations[0].url == "https://src0.com"

    def test_summary_from_seo_result(self) -> None:
        article = assemble_canonical_article(_make_draft(), _make_topic())

        assert (
            article.summary
            == "AI security is evolving rapidly with new threat vectors."
        )

    def test_provenance_from_seo_result(self) -> None:
        draft = _make_draft()
        article = assemble_canonical_article(draft, _make_topic())

        assert article.provenance.primary_model == "claude-opus-4"
        assert article.provenance.drafting_model == "claude-sonnet-4"

    def test_visuals_populated_from_parameter(self) -> None:
        topic = _make_topic()
        draft = _make_draft()
        visuals = [
            ImageAsset(url="/charts/test.png", caption="Test chart", alt_text="Chart"),
        ]
        article = assemble_canonical_article(draft, topic, visuals=visuals)
        assert len(article.visuals) == 1
        assert article.visuals[0].caption == "Test chart"

    def test_visuals_default_to_empty(self) -> None:
        topic = _make_topic()
        draft = _make_draft()
        article = assemble_canonical_article(draft, topic)
        assert article.visuals == []

    def test_visuals_empty(self) -> None:
        article = assemble_canonical_article(_make_draft(), _make_topic())

        assert article.visuals == []

    def test_validation_warns_below_word_count(self) -> None:
        """Low word count logs a warning but does not raise."""
        draft = _make_draft()
        draft.section_drafts = [_make_section(i, 100) for i in range(4)]
        article = assemble_canonical_article(draft, _make_topic())
        assert article is not None

    def test_validation_warns_below_citation_count(self) -> None:
        """Low citation count logs a warning but does not raise."""
        draft = _make_draft()
        draft.global_citations = _make_global_citations(3)
        article = assemble_canonical_article(draft, _make_topic())
        assert article is not None
